In [ ]:
import numpy as np

In [ ]:
#1d array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2d array
b=np.array([[1,2,5],[5,6,7]])
print(b)

[[1 2 5]
 [5 6 7]]


In [ ]:
#3d array
c=np.array([[[1,"one"],[2,"two"],[3,"three"]]])
print(c)

[[['1' 'one']
  ['2' 'two']
  ['3' 'three']]]


In [ ]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#zeros

np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.full((4,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [ ]:
#eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#linspace evenly spaced (default=50 val) inclusive of no.s
np.linspace(0,10,num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
na=[1,2,3]
np.empty_like(na)



array([103984509,         0,        48])

In [ ]:
# prompt: use geomspace

import numpy as np

# geomspace
# Numbers spaced evenly on a log scale (a geometric progression).
np.geomspace(1, 1000, num=4)


array([   1.,   10.,  100., 1000.])

In [ ]:

#copy() creates a new array object that is a copy of the original array.
# Modifications to the copy will not affect the original array, and vice versa.
s=[90,20]
a_copy = s.copy()
a_copy[0] = 10  # Modify the copy

print("Original array 'a':", s)  # Original array remains unchanged
print("Copied array 'a_copy':", a_copy) # Copied array is modified


Original array 'a': [90, 20]
Copied array 'a_copy': [10, 20]


In [ ]:
arr=([[1,2,3,4],[5,6,7,8]])
arr[1:]


[[5, 6, 7, 8]]

In [ ]:
#rand : bw 1 n 0
np.random.rand(2,4)

array([[0.3807981 , 0.13643157, 0.48160604, 0.62111098],
       [0.13165015, 0.93359004, 0.21019795, 0.16943535]])

In [ ]:
#randn : between -3 n +3
np.random.randn(4)

array([ 2.56297983,  1.80275248,  1.27485718, -1.35472373])

In [ ]:
#randint
np.random.randint(1,50,3)

array([25, 35,  5])

In [ ]:
#range
l1=list(range(5))
print(l1)

[0, 1, 2, 3, 4]


In [ ]:
#arange
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
#index
a=np.array([11,2,3,45,5])
print(a[0])

11


In [ ]:
#reshape
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#min, max,sum
arr=np.array([1,2,3,4])
a=np.min(arr)
b=np.max(arr)
print(a)
print(b)
c=np.sum(arr)
print(c)

1
4
10


In [ ]:

# Create a sample array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Extract the diagonal elements
diagonal_elements = np.diag(arr)

diagonal_elements


array([1, 5, 9])

In [ ]:
#diagflat
a= np.diagflat([[1,2],[3,5]])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]


In [ ]:
arr = np.arange(1, 10, 2)
print(arr)


[1 3 5 7 9]


In [ ]:
#tri
np.tri(4, 4, 2, dtype=int)


array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#tril
np.tril([[1,2,3,6],[4,5,6,7],[7,8,9,10],[6,4,5,6]])

array([[0, 0, 0, 0],
       [4, 0, 0, 0],
       [7, 8, 0, 0],
       [6, 4, 5, 0]])

In [ ]:
#triu
np.triu([[1,2,3,6],[4,5,6,7],[7,8,9,10],[6,4,5,6]])

array([[ 1,  2,  3,  6],
       [ 0,  5,  6,  7],
       [ 0,  0,  9, 10],
       [ 0,  0,  0,  6]])

In [ ]:
#indexing n slicing
a="hello"
b=print(a[1:3])
c=print(a[2:])
d=print(a[0])

el
llo
h


In [ ]:
#bmat
A = np.asmatrix('1 1; 1 1')
B = np.asmatrix('2 2; 2 2')
C = np.asmatrix('3 4; 5 6')
D = np.asmatrix('7 8; 9 0')
np.bmat('A,B; C,D')

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [ ]:
a=[1,2,3,4]
a[0:3]

[1, 2, 3]

In [ ]:
import numpy as np
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
arr[:,1]
arr[]


array([20, 50, 80])