In [ ]:
import pandas as pd
import numpy as np
s=pd.Series([2,3,4,5])
print(s)

0    2
1    3
2    4
3    5
dtype: int64


In [ ]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])
print(df)


   Column1  Column2  Column3
0        1        2        3
1        4        5        6
2        7        8        9


In [ ]:

# Accessing a column by name
print(df['Column2'])
row=df.loc['']
print(row)



0    2
1    5
2    8
Name: Column2, dtype: int64
Column1    1
Column2    2
Column3    3
Name: 0, dtype: int64


0    1
1    4
2    7
Name: Column1, dtype: int64

In [ ]:
data_dict = {
    'A': np.array([1, 2, 3]),
    'B': np.array([4, 5, 6]),
    'C': np.array([7, 8, 9])
}
df_dict = pd.DataFrame(data_dict)
print(df_dict)


   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9


In [ ]:
import pandas as pd

# Manually assigned data
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Hannah", "Ian", "Jack"],
    "Age": [25, 30, 22, 28, 35, 40, 27, 32, 29, 31],  # Manually assigned ages
    "Location": ["New York", "Los Angeles", "Chicago", "Houston", "Miami",
                 "Dallas", "Seattle", "Boston", "Boston", "San Francisco"]
}

# Create DataFrame
df = pd.DataFrame(data)

# Print DataFrame
print(df.at[0,'Name'])


Alice


In [ ]:
df['salary']=[100,200,300,400,500,500,505,500,600,1000]
#print(df)
highsal=df[df['salary']>300]
print(highsal)

     Name  Age       Location  salary
3   David   28        Houston     400
4    Emma   35          Miami     500
5   Frank   40         Dallas     500
6   Grace   27        Seattle     505
7  Hannah   32         Boston     500
8     Ian   29         Boston     600
9    Jack   31  San Francisco    1000


In [ ]:
sortdf=df.sort_values(by='Age')
print(sortdf)

      Name  Age       Location  salary
2  Charlie   22        Chicago     300
0    Alice   25       New York     100
6    Grace   27        Seattle     505
3    David   28        Houston     400
8      Ian   29         Denver     600
1      Bob   30    Los Angeles     200
9     Jack   31  San Francisco    1000
7   Hannah   32         Boston     500
4     Emma   35          Miami     500
5    Frank   40         Dallas     500


In [ ]:
avgage=df.groupby('Location')['Age'].mean()
print(avgage)

Location
Boston           30.5
Chicago          22.0
Dallas           40.0
Houston          28.0
Los Angeles      30.0
Miami            35.0
New York         25.0
San Francisco    31.0
Seattle          27.0
Name: Age, dtype: float64


In [ ]:
dfdr=df.drop('Age',axis=1)
print(dfdr)

      Name       Location  salary
0    Alice       New York     100
1      Bob    Los Angeles     200
2  Charlie        Chicago     300
3    David        Houston     400
4     Emma          Miami     500
5    Frank         Dallas     500
6    Grace        Seattle     505
7   Hannah         Boston     500
8      Ian         Boston     600
9     Jack  San Francisco    1000


In [ ]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenating along axis 0 (rows)
result_axis0 = np.concatenate((arr1, arr2), axis=0)

# Concatenating along axis 1 (columns)
result_axis1 = np.concatenate((arr1, arr2), axis=1)

print("Concatenated along axis 0:\n", result_axis0)
print("Concatenated along axis 1:\n", result_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]
